// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.USDAHardinessZone
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("zipCode")]
        public long ZipCode { get; set; }

        [JsonProperty("zone")]
        public string Zone { get; set; }

        [JsonProperty("tempRange")]
        public string TempRange { get; set; }

        [JsonProperty("zoneTitle")]
        public string ZoneTitle { get; set; }

        [JsonProperty("details")]
        public Details Details { get; set; }
    }

    public partial class Details
    {
        [JsonProperty("tempRange")]
        public string TempRange { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("plantSurvival")]
        public string PlantSurvival { get; set; }
    }
}
